### ISSUE TITLE
Coptic font not rendering properly

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/digital-mary#1]
In GitLab by takeda on Feb 12, 2020, 13:12

Coptic text is not rendered properly on Chrome. It shows up as tofu:

Oddly, it renders fine in Firefox:

From what I can gather, the Noto Sans from Google Fonts (the one the site currently uses) does not provide the the Coptic subset that we need for the project; you can download that locally (as the Fonts page says), but I don't think we can ask users to download a font, install, restart, et cetera.

One approach might be to switch to Systems Fonts for the field descriptions, which should have proper handling for language subsets. Something like:

```
font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
```

That fixes it for me (Mac 10.14.16):

But who knows how it would work for older machines, Windows, et cetera.

We could also ask folks on some DH list (maybe the TEI list) to see how others have handled Coptic Fonts--surely someone out there has handled this in the past.

**Comment by joeytakeda** [comment]
In GitLab by takeda on Mar 24, 2020, 16:24

Revisiting this and Systems fonts no longer worked for me. I don't know why and I am confused by all of this.

That said, I *think* I discovered the issue of why Noto Sans didn't work; Google Fonts had a broken path in its CSS declaration, and so that borked the whole thing.

So I think we can use Noto Sans Coptic for this; it'd be easy enough to self-host on the site and we could use it as a fallback. Here's a CodePen showing the language test bit with Georgia and Noto Sans Coptic as a fallback: https://codepen.io/jtakeda/pen/PoqyByV.

**Comment by joeytakeda** [comment]
In GitLab by takeda on Mar 24, 2020, 17:18

Interestingly--and confusingly--the Systems Font approach works on Firefox and Safari and Edge (on Windows), but not on  Chrome 80.0.3987.149 or Edge (Mac). But the Noto Sans thing works on all of them, so that seems the most reliable and backwards/forwards compatible.

**Comment by ubermichael** [comment]
Moved to sfu-dhil/new-digital-mary

**Comment by ubermichael** [comment]
The most recent PR has fixed it, so closing this.

see https://github.com/sfu-dhil/digital-mary/pull/41
