### ISSUE TITLE
Use better font for the original inscriptions

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/digital-mary#21]
The original transcriptions--which could happen in a number of languages--should use a better font. SH and AC suggest using "Athena Ruby" Inscription font:

https://www.doaks.org/resources/athena-ruby

Licensing shouldn't be an issue (CC BY-SA 3.0):

> Dumbarton Oaks, Trustees for Harvard University, Washington, D.C., holds all rights to Athena Ruby, and makes the font available to the public for free under a [Creative Commons Attribution-ShareAlike 3.0 Unported License](https://www.doaks.org/resources/athena-ruby/users-manual). We request that anyone using the font in a publication, print or digital, formal or informal, include the following acknowledgment (with the version number in parentheses, and if used in a digital publication a link to the Dumbarton Oaks website):
> > This publication uses the font Athena Ruby (ver. x.x), courtesy Dumbarton Oaks, Trustees for Harvard University, Washington, D.C.

(2nd para: https://www.doaks.org/resources/athena-ruby/users-manual)

We will need to clarify where that acknowledgement needs to go. It could be a tooltip on the inscription itself, or in the footer, or potentially in on an About page of some sort.

I don't think Athena covers the entire Coptic character set (see #1), so we will still need to deal with Coptic fonts too.

**Comment by ubermichael** [comment]
I like the idea of putting this on an acknowledgements page.

**Comment by ubermichael** [comment]
Wikipedia says that the [Coptic block](https://en.wikipedia.org/wiki/Coptic_(Unicode_block)) runs from U+2C80 to U+2CFF, the [Greek and Coptic block](https://en.wikipedia.org/wiki/Greek_and_Coptic) runs U+0370..U+03FF. The difference between the two is not clear. There is also a block of [Coptic Epact Numbers](https://en.wikipedia.org/wiki/Coptic_Epact_Numbers) from U+102E0 to U+102FF.

The [Athena Ruby manual](https://www.doaks.org/resources/athena-ruby/users-manual) says it covers (among other things) U+0300 to U+03E1, so that's most (but not all!) of the Greek and Coptic block. It doesn't cover any of the Coptic block as far as I can tell. And it doesn't look like it covers the numbers.

**Comment by joeytakeda** [comment]
Google's Noto Sans Coptic looks like it covers the entire Coptic block (or at least seems to--see attached character map file), so Athena Ruby + Noto Sans should cover the Greek and Coptic block. But numbers are also not supported by Noto Sans Coptic either.

But interestingly

> Athena Ruby does not support Greek characters that are not attested in Byzantine inscriptions. Thus, for example, it is missing the digamma (U+03DC), sho (U+03F7), and san (U+03FA). It also lacks the full set of ASCII characters.

This may not be an issue, but we'll need to be careful about stacking these fonts properly. 

So we'd probably want to sequence these such that Athena Ruby is default, then Noto Sans Coptic, and then something else for numbers/all other characters. (Maybe Noto Sans just for consistency's sake or whatever the default body font is [current Nunito Sans]).

One other thing to consider (and probably a separate ticket) is handling for these characters in the text editor. We could create a character keyboard map keyboard thing; or we could just rely on copy+paste, but we'd have to make sure that whatever source font is used on the text doesn't carry over into the pasted block.

**Comment by joeytakeda** [comment]
The Greek font has been put in--and looks quite nice--but there's a bit of a snag insofar as not _all_ of the inscription is itself in Greek. Items that have multiple inscriptions (i.e. on the obverse and reverse of the item, which each correlate to an image) will often feature some sort of label. For instance in item 102, there's this:

> transliteration: Κύριε, 

So when that gets put into the Greek font, "transliteration" (aptly!) renders Greek-like, so we'll need to think of some way to resolve that.

**Comment by joeytakeda** [comment]
The solution, as best as I can tell, is to subset the Athena Ruby font, which can be done in pure CSS: 

```
 unicode-range: U+005B-0060, U+007B-007E, U+00A0, U+00B7, U+02C1, U+02CA, U+02CB, U+02D9, U+0300-03E1, U+1F00-1FFE, U+200C,
  U+200D, U+2180, U+25CC, U+2627, U+2E09, U+2E0A, U+2E23, U+E100-E823, U+10182, U+10184;
```

These are all of the unicode ranges supported by Athena Ruby (per their documentation) with the exception of `[A-Za-z]`. (There's no way to specify exclusions in the unicode-range, so we have to include the character ranges we need explicitly).

My guess is that we'll have to do something similar for #1, since those will also likely contain headings that need to be rendered not in the Coptic font.
