### ISSUE TITLE
Add spellchecking to WYSWIG forms

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/digital-mary#24]
Per SH: it would be helpful to have some form of spellchecking on the descriptions, et cetera, to make proofing a bit easier. 

The easiest way to do this is to simply turn `browser_spellcheck` on; it won't be totally accurate and won't take the place of proofing, but at least it will at least catch common typos (teh vs the, for instance).

**Comment by joeytakeda** [comment]
Added in https://github.com/joeytakeda/digital-mary/commit/d8607507c2f73b6d6b7b48b1e4e4e2cb98e8cf56. Tested and seems to work fine in Chrome and Firefox.

**Comment by ghost** [comment]
Ok. Is this something we should enable everywhere? I don't really see a reason not to.

**Comment by ubermichael** [comment]
I checked just now, and this is enabled in the server, so I'm going to close this one.

**Comment by ubermichael** [comment]
Oh, and it looks like it's enabled everywhere.
