### ISSUE TITLE
Finalize prototype design with tweaks requested by PI from last meeting

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/digital-mary#30]
- [x] SH and AC to check citation format
- [x] Make credits state “Anything who’s edited this record”
- [x] JT to add descriptive hover for image viewer icons
- [x] JT to delete the “download image” button
Replace that to a “link out” to the original source of the image (e.g., British Museum)
- [x] Image Information should be opened for ALL images (of multi-images items) once the user opens one

**Comment by joeytakeda** [comment]
@rcastong could you split these into multiple tickets?

**Comment by ghost** [comment]
Separate tickets please, with "Replace that to a “link out” to the original source of the image (e.g., British Museum)" assigned to me. I don't think we have a field for the original source of the image.

**Comment by joeytakeda** [comment]
I've checked off the items above that have been completed already (they're piled in a number of commits). I've also removed the "Download" button from public view for the time being, so I think the only two tickets that need to be made are the popovers for the image icons and adding a link field for the image. I'll make those two tickets and then close this one.

**Comment by joeytakeda** [comment]
I've added two new tickets (#32 and #33) for the remaining items, so closing this now.

**Comment by rcastong** [comment]
darn, I missed that this was closed! I created new issues that, well, I closed right away!
