### ISSUE TITLE
Consider ability to link to sources from item/images

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/digital-mary#32]
At the last meeting, we discussed that images should have a link field that can point to the original source for that image; I imagine this will be the catalogue record or source for the image, not the image itself (the latter case should be done using remote images). 

However, now that I think about this a bit more carefully, I'm not sure if the link should be on the image or on the item. The original request stemmed from not wanting a download button for the image for public viewing, but there's no reason why there needs to be any link on the image at all. If we do need a mechanism for point to a catalogue record, it may more sense (and be more honest) if the pointer is from DM item to external catalogue record rather than each image having a link (which may end up being the same link).

**Comment by joeytakeda** [comment]
I haven't set a milestone for this, since I'm not sure if this is necessary for PHASE 1.

**Comment by ubermichael** [comment]
I agree with your thinking here. There should be a link on the item to the catalogue record.

**Comment by ubermichael** [comment]
Do you think it would be enough to include the link in the text of the location field? That seems the most natural thing to me.

**Comment by joeytakeda** [comment]
I think if the link goes to the holding institution, then the location makes perfect sense. But if it's meant to say "We got this the entire item's information from this resource" or "Go here to see where we got the image from," that may be slightly different.

My best guess is that link should probably go on the item, but what do you think, @sabrinahiggins ? Should the link be attached to a particular field (like location), the image, or the whole item?

**Comment by rcastong** [comment]
Question: if the image comes from an external source, say the MetMuseum, would clicking on the image bring up the image viewer or would it just link out automatically to the museum site? 

My 2c on that is that users have a "natural" reflex to click on images. If a user does that and nothing happens they might not look for a link somewhere else.

**Comment by joeytakeda** [comment]
There’s two types of images at the moment: images uploaded to the database and remote images, which are meant to be images that we can hotlink to but can’t download for licensing reasons. There aren’t any remote images at the moment, though.  

For the images in the database, the behavior is that when people click on the image, it should open the zoom-y image viewer. The link would be a separate thing: my thinking is that the link is really connected to the item in some way (it might link to the holding institution’s catalogue entry or something else) but it probably wouldn’t be associated with the image (since items can have multiple images).

**Comment by rcastong** [comment]
I'm guessing that you cannot have 2 different behaviours depending on whether the image is "local" or "remote". If so, the link as part of the item record (a separate URL field perhaps) sound like the right solution.

**Comment by sabrinahiggins** [comment]
I'm happy with this solution Remi. I think having a separate URL field to link to an image, for which we don't have permission, might be the best option. These links will have to be monitored on our end, since (as we know from the British Museum) museums will often update their websites and render their links useless, but I think it's the best solution.

**Comment by ghost** [comment]
I think this is what the Remote Images feature is for. Is there something not right with that feature?

**Comment by joeytakeda** [comment]
Clarification from the meeting last week:

* Remote images will simply be links, but are only going to be included iff there is no local image (i.e. "local" image and remote images are mutually exclusive)
* There are no real remote images yet, but there may be more in the future

My main task is (well, was--I've done this now: see #38 for more details) to create a placeholder image for the image; that task is detailed in #38, so I'm going to close this ticket.
