### ISSUE TITLE
Icons should have descriptive/explanatory text

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/digital-mary#33]
Icon buttons in the image viewer (and probably elsewhere, too) should have some sort of popover or descriptive text to explain their function. Best practice would probably be to have a caption directly under each icon, but that might not feasible for the image viewer, which may just need to have popovers or something else. Though I'm not sure how well popovers will play with the image viewer code.

Another option may be to have a HELP or INFO button somewhere that explains what each button does.

**Comment by ubermichael** [comment]
Fixed in 463c4fc
