### ISSUE TITLE
Add better README

### ISSUE THREAD

**Issue by joeytakeda** [sfu-dhil/digital-mary#43]
The repository needs a README with some basic info in it. It won't be full documentation, but it should cover the basics who/what/where/whens. 

Probably should contain

* The name of the project / the PI / the institution
* The acknowledgement for use of Athena Ruby font for Greek typeface
* Basic technical info (i.e. You need to do `composer install` and `yarn install`; If you want to update the style, you should use `sass --watch`.)

**Comment by ubermichael** [comment]
It probably needs a bit about `./bin/console nines:font:download` as well. Because that stuff is too confusing.
